### ISSUE TITLE
I had to transform my database a bit but I got it working...

### ISSUE THREAD

**Issue by DesktopMasters** [IOKernel/MoveSonarrDB#1]
I am sharing this in case someone else ran into my issue and how I fixed it...

So on my Windows machine everything is stored under..
C:\Storage\Shows
C:\Storage\Shows - Complete
C:\Storage\Shows - Kids
etc....

On the linux box it was all stored under /Media
When I ran the script it would crash out with an error...
`Traceback (most recent call last):
  File "../../fixdb.py", line 76, in <module>
    Series()
  File "../../fixdb.py", line 28, in Series
    directory, filename = row[0][3:].split("\\")
ValueError: too many values to unpack
`

I solved this by editing the database on the Windows machine through Sonarr.  I created empty placeholder folders on the C drive for C:\Shows, C:\Shows - Complete, etc... and then edited the database through Sonar pointing the shows at those folders.  (Remember you can select multiple shows by click/checking the first and SHIFT/clicking/checking the last one.  Once all my main folders were moved to the root of the C:\ I was able to then backup and run the script on the database with no trouble.  It also goes without saying that I edited the script its self changing the variable and if statements to match my /Media folder as opposed to the original /media folder.

**Comment by IOKernel** [comment]
When I created the script I designed it around my file pathing and I had everything directly on the drive  
- D:\Shows
- E:\Shows
- D:\Movies  
  
I didn't expect anyone to find this git so I haven't added many instructions. Hope you figured it out, updated the readme with the new instructions.
